/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        sf: {
          bg: 'var(--sf-bg)',
          surface: 'var(--sf-surface)',
          'surface-subtle': 'var(--sf-surface-subtle)',
          'surface-inset': 'var(--sf-surface-inset)',
          'surface-raised': 'var(--sf-surface-raised)',
          border: 'var(--sf-border)',
          'border-strong': 'var(--sf-border-strong)',
          'border-subtle': 'var(--sf-border-subtle)',
          text: 'var(--sf-text)',
          body: 'var(--sf-text-body)',
          muted: 'var(--sf-text-muted)',
          subtle: 'var(--sf-text-subtle)',
          inverse: 'var(--sf-text-inverse)',
          accent: 'var(--sf-accent)',
          'accent-hover': 'var(--sf-accent-hover)',
          'accent-text': 'var(--sf-accent-text)',
          'accent-weak': 'var(--sf-accent-weak)',
          'accent-border': 'var(--sf-accent-border)',
          ring: 'var(--sf-ring)',
          ready: 'var(--sf-ready)',
          'ready-text': 'var(--sf-ready-text)',
          'ready-weak': 'var(--sf-ready-weak)',
          progress: 'var(--sf-progress)',
          'progress-text': 'var(--sf-progress-text)',
          'progress-weak': 'var(--sf-progress-weak)',
          complete: 'var(--sf-complete)',
          'complete-text': 'var(--sf-complete-text)',
          'complete-weak': 'var(--sf-complete-weak)',
          locked: 'var(--sf-locked)',
          'locked-weak': 'var(--sf-locked-weak)',
          context: 'var(--sf-context)',
          'context-text': 'var(--sf-context-text)',
          'context-weak': 'var(--sf-context-weak)',
          'needs-inputs': 'var(--sf-needs-inputs)',
          'needs-inputs-text': 'var(--sf-needs-inputs-text)',
          'needs-inputs-weak': 'var(--sf-needs-inputs-weak)',
          upcoming: 'var(--sf-upcoming)',
          'upcoming-text': 'var(--sf-upcoming-text)',
          'upcoming-weak': 'var(--sf-upcoming-weak)',
          trusted: 'var(--sf-artifact-trusted)',
          'trusted-text': 'var(--sf-artifact-trusted-text)',
          'trusted-weak': 'var(--sf-artifact-trusted-weak)',
          'trusted-border': 'var(--sf-artifact-trusted-border)',
          success: 'var(--sf-success)',
          'success-weak': 'var(--sf-success-weak)',
          danger: 'var(--sf-danger)',
          'danger-weak': 'var(--sf-danger-weak)',
          warning: 'var(--sf-warning)',
          'warning-weak': 'var(--sf-warning-weak)',
          info: 'var(--sf-info)',
          'info-weak': 'var(--sf-info-weak)',
          'type-source': 'var(--sf-type-source)',
          'type-reference': 'var(--sf-type-reference)',
          'type-artifact': 'var(--sf-type-artifact)',
          'type-process': 'var(--sf-type-process)',
          'type-decision': 'var(--sf-type-decision)',
          'type-handoff': 'var(--sf-type-handoff)',
          'type-output': 'var(--sf-type-output)',
          'type-archive': 'var(--sf-type-archive)',
        },
      },
      fontFamily: {
        sans: ['var(--sf-font-sans)'],
        mono: ['var(--sf-font-mono)'],
      },
      boxShadow: {
        'sf-sm': 'var(--sf-shadow-sm)',
        'sf-md': 'var(--sf-shadow-md)',
        'sf-lg': 'var(--sf-shadow-lg)',
        'sf-glow': 'var(--sf-shadow-glow)',
      },
      letterSpacing: {
        'sf-wide': 'var(--sf-tracking-wide)',
        'sf-widest': 'var(--sf-tracking-widest)',
      },
    },
  },
  plugins: [],
}

